### ISSUE TITLE
[RN 0.40] Does not compile on iOS

### ISSUE THREAD

**Issue by farazs** [tkporter/react-native-fabric-twitterkit#22]
Due to the required changes in iOS header imports for react-native version >= 0.40 this does not compile anymore.

Errors:
`RCTBridge.h:65:1: Duplicate interface definition for class 'RCTBridge'`

All react native imports need to be changed for eg. from `#import "RCTBridgeModule.h"` to `#import "<React/RCTBridgeModule.h>"`

**Comment by farazs** [comment]
Fixed by #21

**Comment by zachrnolan** [comment]
This is still an issue for me on RN 0.42.3 with react-native-fabric-twitterkit 0.1.1.

Also getting errors "Property has a previous declaration"

**Comment by choru-k** [comment]
@zachrnolan This version is not published on npm. 

Run
```sh
react-native unlink react-native-fabric-twitterkit
npm uninstall react-native-fabric-twitterkit
```

Edit your package.json like this
```
"react-native-fabric-twitterkit": "git://github.com/tkporter/react-native-fabric-twitterkit.git",
```

And run
```sh
npm i
react-native link react-native-fabric-twitterkit
```

In my case, I solved problem on this way.

**Comment by farazs** [comment]
yeah I'm still using my fork because a new version was never published.

**Comment by tkporter** [comment]
Just published the current master to v0.1.2. Let me know if there are any issues!

**Comment by zachrnolan** [comment]
@g6ling @farazs @tkporter Thanks everyone, npm works now.

**Comment by GeoffreyPlitt** [comment]
Package.json still says 0.1.1
